// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGSL5KSk__jrGe88P76rCKvl_zLunbLCc',
    appId: '1:1019326755692:web:aeefe9a83481b2b7317949',
    messagingSenderId: '1019326755692',
    projectId: 'dalel-a0810',
    authDomain: 'dalel-a0810.firebaseapp.com',
    storageBucket: 'dalel-a0810.appspot.com',
    measurementId: 'G-F41VF7CX1J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLHhZ0aQPX6R0I0uhqvPFLG2u3wzbDNmI',
    appId: '1:1019326755692:android:7a154ea97df3588e317949',
    messagingSenderId: '1019326755692',
    projectId: 'dalel-a0810',
    storageBucket: 'dalel-a0810.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp66G4AJrR4tlKTee31H56RCKeJmztjm8',
    appId: '1:1019326755692:ios:69a10ba0acbfefa9317949',
    messagingSenderId: '1019326755692',
    projectId: 'dalel-a0810',
    storageBucket: 'dalel-a0810.appspot.com',
    iosBundleId: 'com.example.dalelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAp66G4AJrR4tlKTee31H56RCKeJmztjm8',
    appId: '1:1019326755692:ios:69a10ba0acbfefa9317949',
    messagingSenderId: '1019326755692',
    projectId: 'dalel-a0810',
    storageBucket: 'dalel-a0810.appspot.com',
    iosBundleId: 'com.example.dalelApp',
  );
}
